HIT-34297 Allow hard delete on contact resource
Helpling/freshdesk-rest pull request #6
Opened 2024-02-14 08:46 UTC by arfrancisco

https://helpling.atlassian.net/browse/HIT-34297

We need a way to hard delete contacts on H2.

For reference:
https://developers.freshdesk.com/api/#hard_delete_contact

2024-02-14 09:03 UTC, d4rky-pl requested changes

2024-02-14 09:03 UTC, d4rky-pl commented on lib/freshdesk-rest/resource/contact.rb
> +        end
Please make the `force` into a parameter, this should be configurable. Additionally, use `path_with_params` for this.

2024-02-14 10:29 UTC, d4rky-pl approved these changes
LGTM! Don't forget to bump the version number before release 👍

2024-02-14 10:30 UTC, merged

2024-03-12 14:21 UTC, artem-boltunov-h commented on lib/freshdesk-rest/resource/contact.rb
> +        def hard_delete(id:, force: false)
@arfrancisco I'm curious, in case we pass force as true, then it wouldn't be `hard_delete` ?

2024-03-12 15:07 UTC, d4rky-pl commented on lib/freshdesk-rest/resource/contact.rb
> +        def hard_delete(id:, force: false)
@artem-boltunov-h the `force` here comes directly from Freshdesk API. By default a contact needs to be soft deleted first before getting hard deleted, the `force` flag makes it happen in one API call instead of two